#cloud-config
hostname: ubuntu-terraform-lite
fqdn: ubuntu-terraform-lite.lab.local
manage_etc_hosts: true

# Template: Use Terraform Variable
chpasswd:
  list: |
    ubuntu:${vm_password}
  expire: False

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, wheel
    shell: /bin/bash
    lock_passwd: false

package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - net-tools
  - curl

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

final_message: "The system is finally up, after $UPTIME seconds"
